### ISSUE TITLE
Command Failed Error

### ISSUE THREAD

**Issue by adambyer** [opentok/archiving-composer#13]
Hi, I'm using this for the first time. I've followed the instructions in the readme, but I'm getting the following error when running the command like this...

`./archiving-composer/composer.js -i archive.zip -f mp4`

```
ffmpeg -y -threads 4 -loglevel quiet -ss 0 -t 8.277 -i archive/607a66e6-3323-44f2-abb8-25f14c8c8c2f.webm -filter_complex "[0]scale=640:-1[b];[b]drawtext=fontsize=30:fontcolor=white:fontfile=/Library/Fonts/Tahoma.ttf:text='{"user_hash": "GyB", "user_id": 47, "match_hash": "wQd9", "match_id": 2064}':x=w/2-text_w/2:y=h-line_h-5" -shortest temp-0-8277.mp4
child_process.js:644
    throw err;
    ^

Error: Command failed: ffmpeg -y -threads 4 -loglevel quiet -ss 0 -t 8.277 -i archive/607a66e6-3323-44f2-abb8-25f14c8c8c2f.webm -filter_complex "[0]scale=640:-1[b];[b]drawtext=fontsize=30:fontcolor=white:fontfile=/Library/Fonts/Tahoma.ttf:text='{"user_hash": "GyB", "user_id": 47, "match_hash": "wQd9", "match_id": 2064}':x=w/2-text_w/2:y=h-line_h-5" -shortest temp-0-8277.mp4
    at checkExecSyncError (child_process.js:601:13)
    at execSync (child_process.js:641:13)
    at Extract.<anonymous> (/Users/adambyer/01ab/development/test/opentok-archive-composer/archiving-composer/composer.js:202:13)
    at emitNone (events.js:106:13)
    at Extract.emit (events.js:208:7)
    at DirWriter.<anonymous> (/Users/adambyer/01ab/development/test/opentok-archive-composer/archiving-composer/node_modules/unzip/lib/extract.js:38:10)
    at emitNone (events.js:111:20)
    at DirWriter.emit (events.js:208:7)
    at end (/Users/adambyer/01ab/development/test/opentok-archive-composer/archiving-composer/node_modules/fstream/lib/writer.js:323:12)
    at /Users/adambyer/01ab/development/test/opentok-archive-composer/archiving-composer/node_modules/fstream/lib/writer.js:313:32
```

Any idea what I'm doing wrong?
Thanks.

**Comment by h8rry** [comment]
Having the same problem. How did you fix this?

**Comment by muralibobby35** [comment]
Same problem. any luck?

**Comment by muralibobby35** [comment]
I am also getting same error. Please let me know where the problem it is?

**Comment by adambyer** [comment]
Sorry, I am no longer using this and it was a while ago. I am now just installing and running ffmpeg myself.

**Comment by muralibobby35** [comment]
Thanks for your reply. 

How you are composing individual archives into composite archives now? Are you doing css layout management also? 

If you are doing then please let me know how you did that.

**Comment by adambyer** [comment]
I'm now just using the individual archives as-is.
